server:
  port: "${SOA_SERVICE_PORT}"
  ssl:
    key-store-type: "PKCS12"
    key-store: "${KEY_STORE}"
    key-store-password: "${KEY_STORE_PASSWORD}"
    key-alias: "${KEY_ALIAS}"

spring:
  main:
    banner-mode: "off"
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: "update"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      javax:
        persistence:
          validation:
            mode: "auto"
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
