server:
  port: "${SOA_SERVICE_PORT}"
  ssl:
    key-store-type: "PKCS12"
    key-store: "classpath:keystore.p12"
    key-store-password: "changeit"
    key-alias: "springboot"

    trust-store: "classpath:wildfly-truststore.p12"
    trust-store-password: "changeit"
    trust-store-type: "PKCS12"

spring:
  main:
    banner-mode: "off"
  datasource:
    url: "${SOA_SERVICE_BD_URL}"
    username: "${SOA_SERVICE_BD_USERNAME}"
    password: "${SOA_SERVICE_BD_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: "update"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      javax:
        persistence:
          validation:
            mode: "auto"
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
