server:
  port: "${SOA_SERVICE_PORT}"
  ssl:
    key-store-type: "PKCS12"
    key-store: "${KEY_STORE}"
    key-store-password: "${KEY_STORE_PASSWORD}"
    key-alias: "${KEY_ALIAS}"

spring:
  main:
    banner-mode: "off"
  datasource:
    url: "${SOA_SERVICE_BD_URL}"
    username: "${SOA_SERVICE_BD_USERNAME}"
    password: "${SOA_SERVICE_BD_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: "update"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      javax:
        persistence:
          validation:
            mode: "auto"
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
  cloud:
    consul:
      host: "${CONSUL_HOST}"
      port: "${CONSUL_PORT}"
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        health-check-url: "https://localhost:${SOA_SERVICE_PORT}/actuator/health"
        health-check-interval: 10s
        health-check-tls-skip-verify: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
